### ISSUE TITLE
Undo/redo is not working with some commands.

### ISSUE THREAD

**Issue by vansh284** [AY2324S1-CS2103T-W13-1/tp#107]
After an `addsc` or `delsc` command, performing `undo` will result in the last change in the address book being undone. The `undo` should undo the `addsc` command instead in this case.

Similarly, for listing patients/specialists. The undo/redo does not seem to account for the change the `FilteredPersonList` in general.

The undo/redo also does not work for the `view`.  So we cannot go back to the previously viewed person.

Commands that require undo/redo integration :

- [x] addsc/delsc
- [x] view
- [x] theme

**Comment by Kokseng1** [comment]
Should Find and List commands be affected by Undo?

**Comment by vansh284** [comment]
I think having different undo/redo behaviors for different commands just causes more bugs as we saw in the PE-D. Undo/redo should universally affect all commands as intended initially.
