### ISSUE TITLE
PersonType bar showing incorrect behaviour

### ISSUE THREAD

**Issue by alvinlim277** [AY2324S1-CS2103T-W13-1/tp#109]
There are 2 issues with the PersonType bar at the top of the `PersonListPanel`. The behaviour probably arises from the code to update the PersonType bar being located in `PersonListViewCell::updateItem`.

## Issue 1: Bar not updating correctly when executing list commands
Steps to reproduce:
1. Delete all patients from application
2. List all specialists
3. List all patients

Result: The PersonType bar still shows `Specialist` instead of `Patient`.

![image](https://github.com/AY2324S1-CS2103T-W13-1/tp/assets/108080878/5c82491f-8413-40ee-abcb-60d09e7c5cfc)

## Issue 2: Bar does not update unless mouse clicks are performed
Steps to reproduce:
1. Delete all patients from application
2. Relaunch application
3. Add any patient data

(Notice that the PersonType bar does not update)
   
![image](https://github.com/AY2324S1-CS2103T-W13-1/tp/assets/108080878/1c4eea28-2eb7-42b2-b59d-12d13aa542fc)

4. Click on the added patient 

(Only then does the PersonType bar update)

![image](https://github.com/AY2324S1-CS2103T-W13-1/tp/assets/108080878/83ea9104-d1bb-4d02-9275-0cba5e58d5f2)

**Comment by vansh284** [comment]
Seems to me that this should be resolved by refactoring the code around this bar. I also faced similar problems with this when working on the color customization.
