### ISSUE TITLE
Update individual information in AboutUs.md

### ISSUE THREAD

**Issue by Gavino3o** [AY2324S1-CS2103T-W13-1/tp#11]
Let's update the list below so we can close the issue once we are all done.

Progress:
- [x] Vansh
- [x] Gavin
- [x] Alvin
- [x] Kok Seng
- [x] Angky

**Comment by vansh284** [comment]
Added a task progress list. Let's update it timely so we know when to close the issue.

**Comment by vansh284** [comment]
Closed as completed.
