### ISSUE TITLE
[PE-D][Tester D] Explanation in display box is inconsistent.

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W13-1/tp#130]
![image.png](https://raw.githubusercontent.com/jinyuan0425/ped/main/files/474a9a15-69bb-40d4-92c2-87e759be484a.png)

For the parameters portion, only t/TAG is with the square braces (which indicates optional). Perhaps can consider making all with or all without the square brackets for consistency.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: jinyuan0425/ped#5

**Comment by Gavino3o** [comment]
Check `edit` as well. Similar behavior.

**Comment by vansh284** [comment]
Update UG as well to reflect this
