### ISSUE TITLE
[PE-D][Tester E] Lines appearing in background of list panel and view panel

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W13-1/tp#131]
![image.png](https://raw.githubusercontent.com/s0ngyang/ped/main/files/defb137c-0538-4b56-802e-23c4bea85a9b.png)

Steps to reproduce:
1. Enter `theme light`

Horizontal lines are seen in the background of the view panel and list panel in both light and dark mode, though it is especially visible in light mode. Not sure if that is the intended design as the lines seem to be randomly spaced.

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: s0ngyang/ped#3

**Comment by vansh284** [comment]
Not allowed to fix in v1.4
