### ISSUE TITLE
[PE-D][Tester A] Inconsistent Error Message [view command]

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W13-1/tp#136]
![image.png](https://raw.githubusercontent.com/LHeng1/ped/main/files/9b0a11c8-6c1a-4bc9-a073-1e9112c0811c.png)

I first typed in `list -pa`, and after that when an invalid negative integer is typed for `view` command as shown above, the error messaged shown is `Invalid person type! Specify either "-pa" for patient or "-sp" for specialist`, which does not make sense for a user. Perhaps a better error message is to inform the users that an invalid number is used for the view command.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: LHeng1/ped#5

**Comment by Gavino3o** [comment]
Duplicate Issue as #129
