### ISSUE TITLE
[PE-D][Tester D] Inconsistent handling of error inputs

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W13-1/tp#137]
![image.png](https://raw.githubusercontent.com/jinyuan0425/ped/main/files/9e292f0c-2029-4df0-86cb-114bf5cc70a5.png)

![image.png](https://raw.githubusercontent.com/jinyuan0425/ped/main/files/25bac958-e248-4f3b-a657-5f2714ca2be4.png)

For delsc, error inputs are acknowledged but the valid shortcuts are still deleted. However for delete, once there is an error input, even valid indexes are not deleted.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: jinyuan0425/ped#7

**Comment by alvinlim277** [comment]
Feature flaw

**Comment by Gavino3o** [comment]
Update DG documentation, add into "Planned Enhancements". Consider adding to UG
