### ISSUE TITLE
Some bugs in the DG for `find` command

### ISSUE THREAD

**Issue by vansh284** [AY2324S1-CS2103T-W13-1/tp#167]
![image](https://github.com/AY2324S1-CS2103T-W13-1/tp/assets/65393463/01e21352-c630-4b76-bba2-1b089bbc7dc9)
Empty box in `:FindPredicateMap`, can be removed since there are no attributes/predicates (some of the other UML diagrams in the DG have objects with no boxes so can refer)

![image](https://github.com/AY2324S1-CS2103T-W13-1/tp/assets/65393463/2b9da7dd-0358-454a-8cd2-271a8d9a38f0)

- arrow instantiating `FindCommand` has a `m` on top of it. I think `m` was supposed to be the parameter? If so I think the appropriate way would be to write `FindCommand|(m)` as normally the method name of the method being invoked is written on top of the arrow.
- If possible, we should find a way to make the diagram bigger or to remove some extraneous parts of the diagram so we don't get bug reports saying that the uml diagram was unreadable. It's hard to read in the current state because the items are quite small.

**Comment by Gavino3o** [comment]
Thanks for pointing the errors out. Will update by today.
