### ISSUE TITLE
Inconsistent and incomplete error message for optional tags and medical history

### ISSUE THREAD

**Issue by Gavino3o** [AY2324S1-CS2103T-W13-1/tp#172]
![image](https://github.com/AY2324S1-CS2103T-W13-1/tp/assets/95404279/13008bcb-ced8-497a-acc5-17291a0786e8)

![image](https://github.com/AY2324S1-CS2103T-W13-1/tp/assets/95404279/2398789e-00df-42bb-a2f0-a60a04582149)

![image](https://github.com/AY2324S1-CS2103T-W13-1/tp/assets/95404279/3364937d-f6c5-4801-af5f-cb9718a610ab)

## Description
Due to the optional nature of `TAGS` and `MEDICAL_HISTORY`, we allow empty arguments for commands that accept `t/` and `m/` in the `edit` command to clear/remove tags and medical history from records. However, when adding multiple values to both `TAGS` and `MEDICAL_HISTORY`, it does not accept blank arguments. 

## Expected behaviour
Unsure of how the correct behaviour should be. Would love the input from others @vansh284 @alvinlim277 @angkyakdifp @Kokseng1.
Should `add` command accept empty arguments as well?

As for the `edit` command, the error messages need to be updated to be more useful and consistent between TAGS` and `MEDICAL_HISTORY`

**Comment by vansh284** [comment]
I think the empty "m/" or "t/" should be exclusive to the edit command to clear inputs. For add, it's fine sense to disallow users from putting in empty parameters (as long as its specified in the UG)

**Comment by alvinlim277** [comment]
I agree with Vansh, when the user is adding a person if they have typed in `t/` or `m/` they likely intend to add those optional fields anyway. Specifying this in the UG would be good.
