### ISSUE TITLE
UI behaviour when resizing window

### ISSUE THREAD

**Issue by alvinlim277** [AY2324S1-CS2103T-W13-1/tp#98]
Minor issue where the view panel of the UI gets cut off when the window is resized to the minimum size. 

![image](https://github.com/AY2324S1-CS2103T-W13-1/tp/assets/108080878/bd4e59d4-eaf2-4dc9-98a7-c47088655036)

**Comment by Gavino3o** [comment]
Issue is resolved with PR #117
